name: ClassicManhunt
version: 1.0
main: com.Theman75.manhunt.Manhunt
api-version: 1.13
description: Classic Manhunt plugin for 1.12.2 where hunters track the runner.
commands:
  runner:
    description: Set your role to Runner.
    permission: manhunt.use
  hunter:
    description: Set your role to Hunter.
    permission: manhunt.use
